apiVersion: v1
kind: Service
metadata:
  name: python-app-canary
  labels:
    app: python-app
    track: canary
    component: application
spec:
  selector:
    app: python-app
    track: canary
  ports:
    - name: http
      port: 80
      targetPort: 5000
