apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: python-app-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: python-app.rules
      rules:
        - record: job:http_requests:rate1m
          expr: rate(http_requests_total[1m])
