apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - application
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: http
      interval: 30s
